version: '3.8'

services:
  app:
    build: .
    container_name: cerberes_backend
    ports:
      - "8000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/cerberes
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: cerberes_db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cerberes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 