name: CI Pipeline

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    lint_typecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8.6.0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Run lint
              run: pnpm lint

    test:
        runs-on: ubuntu-latest
        needs: lint_typecheck
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8.6.0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test || echo "No tests defined yet" # Allow pipeline to continue if no tests defined

    build:
        runs-on: ubuntu-latest
        needs: [lint_typecheck, test]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8.6.0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Build application
              run: pnpm build

            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build-artifact
                  path: |
                      dist/
                      package.json
                      pnpm-lock.yaml